services:
  spring-boot-backend:
    image: ghcr.io/pscr-kdh/capstone_project_team05_backend
    ports:
      - "8080:8080"
    volumes:
      - "./src/main/resources/static:/app/resources/static"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/capstone-project
      - SPRING_DATASOURCE_USERNAME=capstone-project
      - SPRING_DATASOURCE_PASSWORD=team05
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=capstone-project'
      - 'MARIADB_PASSWORD=team05'
      - 'MARIADB_ROOT_PASSWORD=pjs911800@'
      - 'MARIADB_USER=capstone-project'
    ports:
      - '3308:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: # 마리아DB 데이터를 저장할 이름 있는 볼륨
