name: Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.3'
        java-version: '17'
        github-token: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Add exec permission to gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Upload JAR file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-file
        path: build/libs/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Download JAR file
      uses: actions/download-artifact@v2
      with:
        name: jar-file

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image to GitHub Container Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/capstone_project_team05_backend:latest
