name: Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.3.3'
        java-version: '17'
        github-token: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Add exec permission to gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Build Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
      run: |
        echo $DOCKER_PASSWORD | docker login https://ghcr.io -u $DOCKER_USERNAME --password-stdin
        docker-compose build

    - name: Push Docker image
      run: |
        docker-compose push
